### ISSUE TITLE
Upgrade Charm self-replacement logic needs work

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/layer-easyrsa#4]
During atuomated testing in the upgrade-charm, the deployment log halts with the following output

```
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm EasyRSA-3.0.1/doc/Intro-To-PKI.md
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm ln: failed to create symbolic link '/var/lib/juju/agents/unit-easyrsa-0/charm/EasyRSA/EasyRSA-3.0.1': File exists
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm Traceback (most recent call last):
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm   File "/var/lib/juju/agents/unit-easyrsa-0/charm/hooks/upgrade-charm", line 28, in <module>
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm     main()
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm     bus.dispatch()
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm     _invoke(other_handlers)
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm     handler.invoke()
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm     self._action(*args)
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm   File "/var/lib/juju/agents/unit-easyrsa-0/charm/reactive/easyrsa.py", line 66, in install
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm     check_call(split(link))
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm     raise CalledProcessError(retcode, cmd)
unit-easyrsa-0: 17:38:52 INFO unit.easyrsa/0.upgrade-charm subprocess.CalledProcessError: Command '['ln', '-v', '-s', '/var/lib/juju/agents/unit-easyrsa-0/charm/EasyRSA-3.0.1', '/var/lib/juju/agents/unit-easyrsa-0/charm/EasyRSA']' returned non-zero exit status 1
```
full unit output here: http://paste.ubuntu.com/23227053/

**Comment by chuckbutler** [comment]
Fixed in #5
