### ISSUE TITLE
EasyRSA upgrade-charm error

### ISSUE THREAD

**Issue by lazypower** [juju-solutions/layer-easyrsa#6]
I saw this output during test runs

full unit log here: http://paste.ubuntu.com/23229686/

```
unit-easyrsa-0: 10:26:05 INFO unit.easyrsa/0.upgrade-charm Easy-RSA error:                                                                                                                                                [36/9021]
unit-easyrsa-0: 10:26:05 INFO unit.easyrsa/0.upgrade-charm 
unit-easyrsa-0: 10:26:05 INFO unit.easyrsa/0.upgrade-charm Missing expected CA file: serial (perhaps you need to run build-ca?)
unit-easyrsa-0: 10:26:05 INFO unit.easyrsa/0.upgrade-charm Run without commands for usage and command help.
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm Traceback (most recent call last):
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm   File "/var/lib/juju/agents/unit-easyrsa-0/charm/hooks/upgrade-charm", line 28, in <module>
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm     main()
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm     bus.dispatch()
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm     _invoke(other_handlers)
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm     handler.invoke()
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm     self._action(*args)
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm   File "/var/lib/juju/agents/unit-easyrsa-0/charm/reactive/easyrsa.py", line 226, in create_server_cert
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm     server_cert, server_key = create_server_certificate(cn, sans, name)
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm   File "/var/lib/juju/agents/unit-easyrsa-0/charm/reactive/easyrsa.py", line 263, in create_server_certificate
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm     check_call(split(server))
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm     raise CalledProcessError(retcode, cmd)
unit-easyrsa-0: 10:26:06 INFO unit.easyrsa/0.upgrade-charm subprocess.CalledProcessError: Command '['./easyrsa', '--batch', '--req-cn=104.155.140.245', '--subject-alt-name=IP:104.155.140.245,IP:10.128.0.7,DNS:juju-b6d507-4', 'b
uild-server-full', 'kubeapi-load-balancer_0', 'nopass', '2>&1']' returned non-zero exit status 1
unit-easyrsa-0: 10:26:06 ERROR juju.worker.uniter.operation hook "upgrade-charm" failed: exit status 1
```

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809376.
