### ISSUE TITLE
Scale out broken

### ISSUE THREAD

**Issue by jacekn** [juju-solutions/layer-easyrsa#9]
I use easyrsa with k8s charms. I wanted to scale it out for HA but juju-add-unit easyrsa caused the following hook error:

````
# ./hooks/client-relation-changed 

Easy-RSA error:

Missing expected CA file: serial (perhaps you need to run build-ca?)
Run without commands for usage and command help.
Traceback (most recent call last):
  File "./hooks/client-relation-changed", line 19, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
    bus.dispatch()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
    _invoke(other_handlers)
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
    handler.invoke()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-easyrsa-1/charm/reactive/easyrsa.py", line 226, in create_server_cert
    server_cert, server_key = create_server_certificate(cn, sans, name)
  File "/var/lib/juju/agents/unit-easyrsa-1/charm/reactive/easyrsa.py", line 263, in create_server_certificate
    check_call(split(server))
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./easyrsa', '--batch', '--req-cn=10.25.61.29', '--subject-alt-name=IP:10.25.61.29,IP:10.25.61.29,DNS:juju-555a14-juju2-is-kubernetes-105-6', 'build-server-full', 'kubernetes-worker_0', 'nopass', '2>&1']' returned non-zero exit status 1
````

**Comment by mbruzek** [comment]
It looks like the other easyrsa unit does not have the CA. We may need to change the code so only the leader signs the keys and certs and the other easyrsa units are ready in standby mode. However I do not know if easyrsa supports importing other server's PKI and signing certs. We need to come up with a strategy of how it should work and more testing and investigation are needed here.

@jacekn If you have more experience with easyrsa or have an architectural design that could help this issue, please leave a comment that would be appreciated.

**Comment by hansbogert** [comment]
In my case the common name of the CA is an ip address of the initial host which create the CA certificate, so if that's correct, then high-availability is even more problematic. In fact I experienced a "unknown certificate authority" when trying to do a manual switch from one easyrsa unit to a different one, on a different MAAS node.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809377.
